version: '2'

services: 
  prestashop:
    image: prestashop/prestashop:1.7-7.3-apache
    ports:
      - 8005:80
      - 9001:9000
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    volumes:
      - ./src:/var/www/html/modules/weboTagHint
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=root
      - DB_NAME=prestashop
      - PS_FOLDER_INSTALL=installDirHasToBeRenamed
      - PS_FOLDER_ADMIN=admin1234
      - PS_LANGUAGE=pl
      - ADMIN_MAIL=support@webo.agency
      - ADMIN_PASSWD=password
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost:8005

  mariadb:
    image: mariadb:10.8.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=prestashop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    ports: 
      - 81:80 
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
