---
name: 'Pre-Release'

on:
  push:
    branches:
      - 'main'

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  release:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: write

    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2.3.4'
        with:
          lfs: true

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Build composer
        uses: php-actions/composer@v5
        with:
          php_version: 7.3
          version: 2

      # - name: Install dependencies
      #   run: composer install --prefer-dist

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: 'src'
          filename: '${{ env.REPOSITORY_NAME }}-latest.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
          tag_name: 'latest'
          files: |
            ${{ env.REPOSITORY_NAME }}-latest.zip
